name: PolarTags
description: Update tag-snippets

on:
  workflow_dispatch:

  # Daily at 07:00
  schedule:
    - cron: "0 7 * * *"

jobs:
  PolarTags:
    timeout-minutes: 15
    runs-on: ubuntu-22.04
    steps:
      - name: Update tag-snippets
        uses: eval/actions/polar-tags@main
        with:
          org: eval
        env:
          POLAR_API_TOKEN: ${{ secrets.POLAR_API_TOKEN }}
