name: Strip paywall snippets from Polar articles X days after publishing.

on:
  # Run after every push
  push:
    branches: ["main"]

  # Daily at 07:00
  schedule:
    - cron: "0 7 * * *"

jobs:
  StripPaywalls:
    timeout-minutes: 15
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: StripIt
        uses: eval/actions/strip-polar-paywall@main
        with:
          org: eval
          days-sifactionnce-publish: 0
        env:
          POLAR_API_TOKEN: ${{ secrets.POLAR_API_TOKEN }}
